# Generated by Django 4.1.1 on 2022-10-10 18:05

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import solicitudes.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleSolicitud',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(help_text='Titulo', max_length=40, null=True)),
                ('matricula', models.CharField(default=None, help_text='Matricula', max_length=10)),
                ('nombre', models.CharField(default=None, help_text='Nombre de quien solicita', max_length=200)),
                ('apellido_paterno', models.CharField(default=None, help_text='Apellido paterno', max_length=200)),
                ('apellido_materno', models.CharField(help_text='Apellido materno', max_length=200, null=True)),
                ('correo', models.EmailField(default=None, help_text='Correo electrónico', max_length=200)),
                ('extension', models.CharField(help_text='No de Extensión', max_length=5, null=True)),
                ('telefono', models.CharField(help_text='Telefono de contacto', max_length=11, null=True)),
                ('pautoriza', models.CharField(help_text='Nombre de quien autoriza', max_length=200, null=True)),
                ('descripcion', models.CharField(help_text='Descripción de la solicitud', max_length=500, null=True)),
                ('folio', models.CharField(help_text='Folio generado automaticamente de la solicitud', max_length=6, null=True)),
                ('fecha_sol', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'DetalleSolicitud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Catalogo_Estatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus_descrip', models.CharField(max_length=20, null=True)),
                ('key_name', models.CharField(max_length=200, null=True, unique=True)),
                ('desc_tipo_estatus', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Catalogo_Estatus',
            },
        ),
        migrations.CreateModel(
            name='Catalogo_SubServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Descripcion de SubServicio', max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Catalogo_SubServicio',
            },
        ),
        migrations.CreateModel(
            name='Dashboard_sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True, unique=True)),
                ('title', models.CharField(max_length=50, null=True)),
                ('ordered', models.IntegerField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('active', models.IntegerField(null=True)),
                ('slug', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleServicios',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('solicitud_id', models.IntegerField()),
                ('servicio', models.IntegerField()),
                ('descripcion', models.CharField(max_length=500, null=True)),
                ('subservicios', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Permission_role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Permission_role',
            },
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('key_name', models.CharField(max_length=200, null=True, unique=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Permissions',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('key_name', models.CharField(max_length=200, null=True, unique=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('permissions', models.ManyToManyField(through='solicitudes.Permission_role', to='solicitudes.permissions')),
            ],
            options={
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Descripción de servicio', max_length=200, null=True, unique=True)),
                ('slug', models.CharField(help_text='slug de servicio', max_length=200, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Titulo', max_length=40, null=True)),
                ('matricula', models.CharField(default=None, help_text='Matricula', max_length=10)),
                ('nombre', models.CharField(default=None, help_text='Nombre de quien solicita', max_length=200)),
                ('apellido_paterno', models.CharField(default=None, help_text='Apellido paterno', max_length=200)),
                ('apellido_materno', models.CharField(help_text='Apellido materno', max_length=200, null=True)),
                ('correo', models.EmailField(help_text='Correo electrónico', max_length=200, null=True, validators=[solicitudes.validators.is_email])),
                ('extension', models.CharField(help_text='No de Extensión', max_length=5, null=True)),
                ('telefono', models.CharField(help_text='Telefono de contacto', max_length=11, null=True)),
                ('pautoriza', models.CharField(help_text='Nombre de quien autoriza', max_length=200, null=True)),
                ('descripcion', models.CharField(help_text='Descripción de la solicitud', max_length=500, null=True, validators=[solicitudes.validators.descripcion_validation_sol])),
                ('folio', models.CharField(help_text='Folio generado automaticamente de la solicitud', max_length=6, null=True)),
                ('fecha_sol', models.DateTimeField(auto_now_add=True)),
                ('estatus_update', models.DateTimeField(null=True)),
                ('estatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.catalogo_estatus')),
            ],
            options={
                'verbose_name_plural': 'Solicitud',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Estatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_estatus', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Catalogo_Estatus',
            },
        ),
        migrations.CreateModel(
            name='Ures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ures_ures', models.CharField(max_length=8)),
                ('ures_descrip', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Ures',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=200, null=True, unique=True)),
                ('active', models.BooleanField()),
                ('password', models.CharField(default=None, max_length=300)),
                ('avatar', models.CharField(max_length=60, null=True)),
                ('token', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_serv', to='solicitudes.servicios')),
                ('role', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='role_id', to='solicitudes.roles')),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='SubServicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fec_subservicio', models.DateTimeField(auto_now_add=True, null=True)),
                ('estatus_update', models.DateTimeField(null=True)),
                ('comentario', models.CharField(max_length=150, null=True)),
                ('estatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='solicitudes.catalogo_estatus')),
                ('solicitud', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subservices', to='solicitudes.solicitud')),
                ('subservicio', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subservicio', to='solicitudes.catalogo_subservicio')),
            ],
            options={
                'verbose_name_plural': 'subservicios',
            },
        ),
        migrations.AddField(
            model_name='solicitud',
            name='ures',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.ures'),
        ),
        migrations.AddField(
            model_name='permission_role',
            name='permissions',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='permission', to='solicitudes.permissions'),
        ),
        migrations.AddField(
            model_name='permission_role',
            name='role',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='role', to='solicitudes.roles'),
        ),
        migrations.CreateModel(
            name='Participantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participante', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='participante', to='solicitudes.users')),
                ('subservicio', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sub_servicioParticipantes', to='solicitudes.subservicios')),
            ],
            options={
                'verbose_name_plural': 'Participantes',
            },
        ),
        migrations.CreateModel(
            name='MyFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='', validators=[solicitudes.validators.valid_extension, solicitudes.validators.validate_file_size])),
                ('descripcion', models.CharField(max_length=80, null=True, validators=[solicitudes.validators.descripcion_validation, django.core.validators.MinLengthValidator(0)])),
                ('nombre_archivo', models.CharField(max_length=100, null=True)),
                ('subido', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos_solicitud', to='solicitudes.solicitud')),
            ],
            options={
                'verbose_name_plural': 'MyFile',
            },
        ),
        migrations.CreateModel(
            name='Dashboard_submenus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('icon', models.CharField(max_length=50, null=True)),
                ('active', models.IntegerField(null=True)),
                ('searchable_name', models.CharField(max_length=100, null=True)),
                ('ordered', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='section', to='solicitudes.dashboard_sections')),
            ],
            options={
                'verbose_name_plural': 'dashboard_submenus',
                'unique_together': {('name', 'section')},
            },
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_comment', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(default='', max_length=150, null=True)),
                ('tipo', models.CharField(max_length=20, null=True)),
                ('subservicio', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sub_serviciocomentario', to='solicitudes.subservicios')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_coment', to='solicitudes.users')),
            ],
            options={
                'verbose_name_plural': 'Comentarios',
            },
        ),
        migrations.AddField(
            model_name='catalogo_subservicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subservicios', to='solicitudes.servicios'),
        ),
        migrations.AddField(
            model_name='catalogo_estatus',
            name='tipo_estatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.tipo_estatus'),
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150, null=True)),
                ('fecha_bitacora', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comment_bit', to='solicitudes.comentarios')),
                ('subservicio', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sub_serviciobit', to='solicitudes.subservicios')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_bit', to='solicitudes.users')),
            ],
            options={
                'verbose_name_plural': 'Bitacora',
            },
        ),
        migrations.AlterUniqueTogether(
            name='permission_role',
            unique_together={('permissions', 'role')},
        ),
        migrations.CreateModel(
            name='Dashboard_links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null=True)),
                ('route', models.CharField(max_length=200, null=True)),
                ('ordered', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('active', models.IntegerField(null=True)),
                ('permission', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='permission_id', to='solicitudes.permissions')),
                ('submenu', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='submenu_id', to='solicitudes.dashboard_submenus')),
            ],
            options={
                'verbose_name_plural': 'dashboard_links',
                'unique_together': {('name', 'submenu')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='catalogo_subservicio',
            unique_together={('servicio', 'descripcion')},
        ),
    ]
