# Generated by Django 4.1.1 on 2022-10-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraServicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.CharField(max_length=40)),
                ('folio_sistema', models.CharField(max_length=40)),
                ('solicitado_por', models.CharField(max_length=40)),
                ('folio_interno', models.CharField(max_length=40)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('solicitud', models.CharField(max_length=200)),
                ('diagnostico', models.CharField(max_length=200)),
                ('material', models.CharField(max_length=200)),
            ],
        ),
    ]
