# Generated by Django 3.2.6 on 2025-02-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_bitacoraservicios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitud',
            options={'verbose_name_plural': 'solicitud'},
        ),
        migrations.AddField(
            model_name='solicitud',
            name='area',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
