# Generated by Django 4.1.1 on 2022-10-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoraservicios',
            name='area',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bitacoraservicios',
            name='puesto',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bitacoraservicios',
            name='recibido_por',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bitacoraservicios',
            name='supervisor',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bitacoraservicios',
            name='tecnico',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bitacoraservicios',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
